### ISSUE TITLE
Add a new github release (last one is from 2017)

### ISSUE THREAD

**Issue by m040601** [jwilk/fbcat#19]
First of all thanks for your work in this interesiting tool.

I've been trying  to test it on  my Archlinux system.

But I don't like to use git versions.
Actually my Arch linux distro has packages for fbcat, https://aur.archlinux.org/packages/fbcat
But since it builds on what you officially tag and release on github, we're stuck in 2017.

Now I see that you have a lot of commits in the last 5 years.
You also put a lot of effort in updating the README and github workflows.
So it's a sign you plan and intend maintaining this project.

Could you tag a new release ? Thanks in advance.

https://github.com/jwilk/fbcat/issues/17

**Comment by jwilk** [comment]
Yup, I'll make a new release in a few days.

Thanks for poking me.

**Comment by m040601** [comment]
Thank you for the attention.


One small question about installing and having both,  your fbcat and fbgrab(gunnar), on the same system. There is a name conflict, your fbcat also installs a binary called "fbgrab". Assuming this would be eventually **"handled" and corrected, by my Linux distro package installer, with proper renaming**

Is there any technical reason, or incompatibility for not having both on the same system ?



Currently, on Archlinux:

your fbcat:

https://aur.archlinux.org/packages/fbcat/
https://github.com/jwilk/fbcat
installs 2 binaries, /usr/bin/fbcat and /usr/bin/fbgrab
installs 2 manpages, man fbcat and man fbgrab

gunnar fbgrab:

https://archlinux.org/packages/community/x86_64/fbgrab/
https://github.com/GunnarMonell/fbgrab
installs 1 binary, /usr/bin/fbgrab
installs 1 manpage, man fbgrab

**Comment by jwilk** [comment]
> There is a name conflict, your fbcat also installs a binary called "fbgrab".

This is deliberate. Our `fbgrab` was designed to be a drop-in replacement for Gunnar Monell’s `fbgrab`.

**Comment by jwilk** [comment]
I've just released [0.5.2](https://github.com/jwilk/fbcat/releases/tag/0.5.2).
