### ISSUE TITLE
support for 1bpp depths

### ISSUE THREAD

**Issue by jwilk** [jwilk/fbcat#2]
Please add support for 1bpp, 2bpp and 4bpp modes.

**Comment by GammaGames** [comment]
How do I use this? I don't need color and just want to use the `MONO01` mode, but can't figure out where to set it.

**Comment by dlech** [comment]
You have to have a Linux fbdev driver that supports it. There aren't many nowadays. Mostly for embedded devices and 1990s hardware.

**Comment by GammaGames** [comment]
Oh okay, I figured it was something technical since the only places I could find it referenced was in kernel documentation.
